# ~/.config.alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
blur = true
decorations = "None"

padding.x = 10
padding.y = 10

[font]
size = 16

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[keyboard]
bindings = [{key = "Enter", mods = "Alt", action = "ToggleFullscreen"}]

[general]
import = [
    #"~/.config/alacritty/themes/themes/breeze.toml"
    #"~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
