# ~/.config.alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

[window]
opacity = 1.0
blur = false
decorations = "None"

padding.x = 10
padding.y = 10

[font]
size = 12

#JetBrainsMonoNL Nerd Font
#IosevkaTerm Nerd Font
[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[keyboard]
bindings = [{key = "Enter", mods = "Alt", action = "ToggleFullscreen"}]

# ------------------------------------------------------------------------

