# ~/.config.alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

[window]
opacity = 1.0
blur = false 
decorations = "Full" # Full | None

padding.x = 10
padding.y = 10

[font]
size = 12

#JetBrainsMonoNL Nerd Font
#IosevkaTerm Nerd Font
[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[keyboard]
bindings = [{key = "Enter", mods = "Alt", action = "ToggleFullscreen"}]

# ------------------------------------------------------------------------

# Colors (Hyper)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#F81CE5'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#d0d0d0'

# Bright colors
[colors.bright]
black   = '#808080'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#FFFFFF'
