services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true   # optional
      - RUN_OPTS=          # optional
    volumes:
      - /home/thr/.var/app/org.qbittorrent.qBittorrent/data/qBittorrent/nova3/engines:/config
    ports:
      - "9117:9117"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    volumes:
      - flaresolverr_config:/config
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

volumes:
  flaresolverr_config:
    driver: local

